---
title: "EDA"
output: html_document
date: "2025-11-04"
---

```{r setup, include=FALSE}

library(rmarkdown); library(knitr); library(moments); 
library(scatterplot3d); library(corrplot); library(pso)
library(psych); library(GPArotation); library(lavaan)



knitr::opts_chunk$set(echo = TRUE)

dataset <- read.csv("personality_datasert.csv")

# 

dataset$Personality <- as.numeric(factor(dataset$Personality, level = c("Introvert", "Extrovert"))) - 1

dataset$Drained_after_socializing <- as.numeric(factor(dataset$Drained_after_socializing, level = c("No", "Yes"))) - 1

dataset$Stage_fear <- as.numeric(factor(dataset$Stage_fear, level = c("No", "Yes"))) - 1


dataset
set.seed(123)  # optional for reproducibility
df_sample <- dataset[sample(nrow(dataset), 200), ]
```


```{r}

```


```{r}
cor1 = cor(df_sample)

eigen(cor1)
```

```{r}

summary (df_sample)
#response
#personality
#Friend circle size 
# going outside
# stage fear

#predictive
#time spent alone
# drained after socializing
#post frequency
```

Hello, this is some text describung the next chunk of code *this* is bolded and now this **is italicized**

```{r}
response <- df_sample$Personality

# Predictor variables
predictive <- df_sample[, c("Time_spent_Alone",
                            "Drained_after_socializing",
                            "Post_frequency",
                            "Friends_circle_size",
                            "Going_outside"
                            )]


response <- df_sample[, c("Personality", "Stage_fear")]

res <- cor(response)
pre <- cor(predictive)

corrplot(res)
corrplot(pre)
eigen(res)
eigen(pre)


#predective "time spent alone" due to kaisers rule 
#response we keep personality due to kaisers
# use a heat map with the coorepation matrix
```
```{r}

res_opt <- pca(r = res, nfactors = 1, rotate = "varimax")$loadings[]
res_opt
pre_opt <- pca(r = pre, nfactors = 1, rotate = "varimax")$loadings[]
pre_opt

```

```{r}
res_obl <- pca(r = res, nfactors = 1, rotate = "oblimin")$loadings[]
res_obl
pre_olb <- pca(r = pre, nfactors = 1, rotate = "oblimin")$loadings[]
pre_olb

```

```{r}
res_opt <- pca(r = res, nfactors = 1, rotate = "oblimin")
res_opt
pre_opt <- pca(r = pre, nfactors = 1, rotate = "varimax")
pre_opt
```



